FROM node:20-alpine AS build

WORKDIR /app
ARG VITE_API_BASE_URL=http://localhost:8000/api/v1
ARG VITE_WS_INGEST_URL=ws://localhost:8000/api/v1/ws/ingest
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_WS_INGEST_URL=$VITE_WS_INGEST_URL
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
